version: '3.9'
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=nastya
      - POSTGRES_PASSWORD=pgspgs
      - POSTGRES_DB=market
    ports:
      - "5434:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP порт для приложений
      - "15672:15672" # веб-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: on-failure


  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    volumes:
      - ./auth/migrations:/app/migrations
    environment:
      - DB_DSN=postgres://nastya:pgspgs@db:5432/auth?sslmode=disable
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  products:
    build:
      context: ./products
      dockerfile: Dockerfile
    container_name: market
    volumes:
      - ./products/migrations:/app/migrations
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8081:8081"
    environment:
      - DB_DSN=postgres://nastya:pgspgs@db:5432/market?sslmode=disable
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: on-failure
