basePath: /
definitions:
  github_com_lahnasti_go-market_internal_models.Credentials:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  github_com_lahnasti_go-market_internal_models.Product:
    properties:
      delete:
        type: boolean
      description:
        type: string
      name:
        type: string
      price:
        type: number
      quantity:
        type: integer
      uid:
        type: integer
    required:
    - description
    - name
    - price
    - quantity
    type: object
  github_com_lahnasti_go-market_internal_models.Purchase:
    properties:
      id:
        type: integer
      productId:
        type: integer
      quantity:
        type: integer
      timestamp:
        type: string
      userId:
        type: integer
    required:
    - productId
    - quantity
    - userId
    type: object
  github_com_lahnasti_go-market_internal_models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  github_com_lahnasti_go-market_internal_server_responses.Error:
    properties:
      error:
        type: string
      message:
        type: string
      status:
        type: integer
    type: object
  github_com_lahnasti_go-market_internal_server_responses.Success:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Your API Title
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Выполняет вход пользователя с указанными учетными данными
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/github_com_lahnasti_go-market_internal_models.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Вход пользователя
      tags:
      - Пользователи
  /products:
    get:
      description: Получить список всех продуктов
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Get all products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Добавить новый продукт
      parameters:
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_lahnasti_go-market_internal_models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Add a new product
      tags:
      - products
  /products/{id}:
    delete:
      description: Удалить продукт по ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Delete a product
      tags:
      - products
    get:
      description: Получить продукт по ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Get a product by ID
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Обновить данные продукта
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/github_com_lahnasti_go-market_internal_models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Update a product
      tags:
      - products
  /products/{id}/purchases:
    get:
      description: Возвращает список покупок для указанного продукта
      parameters:
      - description: ID продукта
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Получение списка покупок по продукту
      tags:
      - Покупки
  /purchases:
    post:
      consumes:
      - application/json
      description: Создает новую покупку для указанного продукта
      parameters:
      - description: Данные о покупке
        in: body
        name: purchase
        required: true
        schema:
          $ref: '#/definitions/github_com_lahnasti_go-market_internal_models.Purchase'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Создание покупки
      tags:
      - Покупки
  /users:
    post:
      consumes:
      - application/json
      description: Регистрирует нового пользователя с предоставленными данными
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_lahnasti_go-market_internal_models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Регистрация нового пользователя
      tags:
      - users
  /users/{id}:
    get:
      description: Возвращает профиль пользователя по указанному ID
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Получение профиля пользователя
      tags:
      - Пользователи
  /users/{id}/purchases:
    get:
      description: Возвращает список покупок для указанного пользователя
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_lahnasti_go-market_internal_server_responses.Error'
      summary: Получение списка покупок пользователя
      tags:
      - Покупки
swagger: "2.0"
